[package]
name = "weaver_resolved_schema"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["io"]
io = ["weaver_common/io", "weaver_version/io", "weaver_semconv/io"]

[dependencies]
weaver_common = { path = "../weaver_common", default-features = false }
weaver_version = { path = "../weaver_version", default-features = false }
weaver_semconv = { path = "../weaver_semconv", default-features = false }

thiserror.workspace = true
serde.workspace = true
schemars.workspace = true
log.workspace = true

[dev-dependencies]
serde_json.workspace = true
