[package]
name = "weaver_semconv"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["io"]
io = [
    "dep:ureq",
    "weaver_common/io",
    "jsonschema/resolve-http",
    "jsonschema/resolve-file",
]
openapi = ["utoipa"]

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[dependencies]
weaver_common = { path = "../weaver_common", default-features = false }

serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
thiserror.workspace = true
miette.workspace = true
schemars.workspace = true
regex.workspace = true
globset.workspace = true
itertools.workspace = true
log.workspace = true
url.workspace = true

glob = "0.3.3"
jsonschema = { version = "0.40.0", default-features = false }
saphyr = "0.0.6"             # YAML parser preserving span information (location in file)
utoipa = { workspace = true, optional = true }

# Gated behind io
ureq = { workspace = true, optional = true }

