[package]
name = "weaver_wasm"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "WebAssembly module for OpenTelemetry Weaver semantic convention validation"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
weaver_checker = { path = "../weaver_checker" }
weaver_resolved_schema = { path = "../weaver_resolved_schema", default-features = false }
weaver_forge = { path = "../weaver_forge", default-features = false }
serde.workspace = true
serde_json.workspace = true
